// <auto-generated />
using System;
using JobBoard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBoard.Migrations
{
    [DbContext(typeof(JobBoardContext))]
    [Migration("20251220102756_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JobBoard.Components.Domain.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobListingId")
                        .HasColumnType("int");

                    b.Property<int>("JobSeekerId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Application");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateApplied = new DateTime(2025, 12, 15, 18, 27, 55, 522, DateTimeKind.Local).AddTicks(5471),
                            JobListingId = 1,
                            JobSeekerId = 3,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            DateApplied = new DateTime(2025, 12, 18, 18, 27, 55, 522, DateTimeKind.Local).AddTicks(5506),
                            JobListingId = 2,
                            JobSeekerId = 4,
                            Status = "Reviewed"
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "contact@techcorp.com",
                            CompanyName = "TechCorp",
                            Industry = "Software",
                            Location = "New York, NY",
                            UserId = 2,
                            WebsiteUrl = "https://techcorp.com"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "info@healthplus.com",
                            CompanyName = "HealthPlus",
                            Industry = "Healthcare",
                            Location = "Boston, MA",
                            UserId = 2,
                            WebsiteUrl = "https://healthplus.com"
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FeedBack");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateSubmitted = new DateTime(2025, 12, 20, 18, 27, 55, 522, DateTimeKind.Local).AddTicks(6030),
                            Message = "Great job board, very easy to use!",
                            UserId = 3
                        },
                        new
                        {
                            Id = 2,
                            DateSubmitted = new DateTime(2025, 12, 20, 18, 27, 55, 522, DateTimeKind.Local).AddTicks(6032),
                            Message = "I love how easy it is to post jobs.",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.JobListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("JobListing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatePosted = new DateTime(2025, 12, 20, 18, 27, 55, 522, DateTimeKind.Local).AddTicks(6110),
                            Description = "Develop and maintain web applications using modern frameworks.",
                            EmployerId = 1,
                            Industry = "Software",
                            JobType = "Full-time",
                            Location = "New York, NY",
                            Requirements = "Proficient in C#, ASP.NET, and React.",
                            Salary = 80000,
                            Title = "Frontend Developer"
                        },
                        new
                        {
                            Id = 2,
                            DatePosted = new DateTime(2025, 12, 20, 18, 27, 55, 522, DateTimeKind.Local).AddTicks(6114),
                            Description = "Work on APIs and server-side logic.",
                            EmployerId = 1,
                            Industry = "Software",
                            JobType = "Full-time",
                            Location = "San Francisco, CA",
                            Requirements = "Experience with C#, .NET Core, SQL Server.",
                            Salary = 85000,
                            Title = "Backend Developer"
                        },
                        new
                        {
                            Id = 3,
                            DatePosted = new DateTime(2025, 12, 20, 18, 27, 55, 522, DateTimeKind.Local).AddTicks(6116),
                            Description = "Analyze data to provide actionable insights.",
                            EmployerId = 2,
                            Industry = "Finance",
                            JobType = "Part-time",
                            Location = "Chicago, IL",
                            Requirements = "SQL, Excel, and Power BI experience.",
                            Salary = 60000,
                            Title = "Data Analyst"
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.JobSeeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResumePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JobSeeker");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationLevel = "Bachelor's in Computer Science",
                            Email = "alice.johnson@example.com",
                            Experience = "2 years at TechCorp as Frontend Developer",
                            LinkedInPath = "https://www.linkedin.com/in/alicejohnson",
                            Name = "Alice Johnson",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EducationLevel = "Master's in Data Science",
                            Email = "bob.smith@example.com",
                            Experience = "3 years at DataSolutions as Data Analyst",
                            LinkedInPath = "https://www.linkedin.com/in/bobsmith",
                            Name = "Bob Smith",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = "Admin",
                            Email = "admin@example.com",
                            Role = "Admin",
                            UserName = "AdminUser"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = "Standard",
                            Email = "employer@example.com",
                            Role = "Employer",
                            UserName = "EmployerUser"
                        },
                        new
                        {
                            Id = 3,
                            AccountType = "Standard",
                            Email = "jobseeker@example.com",
                            Role = "JobSeeker",
                            UserName = "JobSeekerUser"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
