// <auto-generated />
using System;
using JobBoard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JobBoard.Migrations
{
    [DbContext(typeof(JobBoardContext))]
    [Migration("20260118135132_RemoveResumePath")]
    partial class RemoveResumePath
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateApplied")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobListingId")
                        .HasColumnType("int");

                    b.Property<string>("JobSeekerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobListingId");

                    b.HasIndex("JobSeekerId");

                    b.ToTable("Application");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateApplied = new DateTime(2026, 1, 13, 21, 51, 30, 532, DateTimeKind.Local).AddTicks(5605),
                            JobListingId = 1,
                            JobSeekerId = "11111111-2222-3333-4444-555555555555",
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            DateApplied = new DateTime(2026, 1, 16, 21, 51, 30, 532, DateTimeKind.Local).AddTicks(5644),
                            JobListingId = 2,
                            JobSeekerId = "22222222-3333-4444-5555-666666666666",
                            Status = "Reviewed"
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.Employer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyLogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("WebsiteUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Employer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyEmail = "contact@techcorp.com",
                            CompanyName = "TechCorp",
                            IdentityUserId = "33333333-4444-5555-6666-777777777777",
                            Industry = "Software",
                            Location = "New York, NY",
                            WebsiteUrl = "https://techcorp.com"
                        },
                        new
                        {
                            Id = 2,
                            CompanyEmail = "info@healthplus.com",
                            CompanyName = "HealthPlus",
                            IdentityUserId = "44444444-5555-6666-7777-888888888888",
                            Industry = "Healthcare",
                            Location = "Boston, MA",
                            WebsiteUrl = "https://healthplus.com"
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.FeedBack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("FeedBack");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateSubmitted = new DateTime(2026, 1, 18, 21, 51, 30, 532, DateTimeKind.Local).AddTicks(6232),
                            IdentityUserId = "11111111-2222-3333-4444-555555555555",
                            Message = "Great job board, very easy to use!"
                        },
                        new
                        {
                            Id = 2,
                            DateSubmitted = new DateTime(2026, 1, 18, 21, 51, 30, 532, DateTimeKind.Local).AddTicks(6237),
                            IdentityUserId = "22222222-3333-4444-5555-666666666666",
                            Message = "I love how easy it is to post jobs."
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.JobListing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatePosted")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployerId")
                        .HasColumnType("int");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salary")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmployerId");

                    b.ToTable("JobListing");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DatePosted = new DateTime(2026, 1, 18, 21, 51, 30, 532, DateTimeKind.Local).AddTicks(6403),
                            Description = "Develop and maintain web applications using modern frameworks.",
                            EmployerId = 1,
                            Industry = "Software",
                            JobType = "Full-time",
                            Location = "New York, NY",
                            Requirements = "Proficient in C#, ASP.NET, and React.",
                            Salary = 80000,
                            Title = "Frontend Developer"
                        },
                        new
                        {
                            Id = 2,
                            DatePosted = new DateTime(2026, 1, 18, 21, 51, 30, 532, DateTimeKind.Local).AddTicks(6409),
                            Description = "Work on APIs and server-side logic.",
                            EmployerId = 1,
                            Industry = "Software",
                            JobType = "Full-time",
                            Location = "San Francisco, CA",
                            Requirements = "Experience with C#, .NET Core, SQL Server.",
                            Salary = 85000,
                            Title = "Backend Developer"
                        },
                        new
                        {
                            Id = 3,
                            DatePosted = new DateTime(2026, 1, 18, 21, 51, 30, 532, DateTimeKind.Local).AddTicks(6413),
                            Description = "Analyze data to provide actionable insights.",
                            EmployerId = 2,
                            Industry = "Finance",
                            JobType = "Part-time",
                            Location = "Chicago, IL",
                            Requirements = "SQL, Excel, and Power BI experience.",
                            Salary = 60000,
                            Title = "Data Analyst"
                        });
                });

            modelBuilder.Entity("JobBoard.Components.Domain.JobSeeker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Experience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkedInPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JobSeeker");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EducationLevel = "Bachelor's in Computer Science",
                            Email = "alice.johnson@example.com",
                            Experience = "2 years at TechCorp as Frontend Developer",
                            IdentityUserId = "11111111-2222-3333-4444-555555555555",
                            LinkedInPath = "https://www.linkedin.com/in/alicejohnson",
                            Name = "Alice Johnson"
                        },
                        new
                        {
                            Id = 2,
                            EducationLevel = "Master's in Data Science",
                            Email = "bob.smith@example.com",
                            Experience = "3 years at DataSolutions as Data Analyst",
                            IdentityUserId = "22222222-3333-4444-5555-666666666666",
                            LinkedInPath = "https://www.linkedin.com/in/bobsmith",
                            Name = "Bob Smith"
                        });
                });

            modelBuilder.Entity("JobBoard.Data.JobBoardUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "11111111-2222-3333-4444-555555555555",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b6cd7cd-737c-49f0-9c7b-1e897043837b",
                            Email = "alice.johnson@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ALICE.JOHNSON@EXAMPLE.COM",
                            NormalizedUserName = "ALICE.JOHNSON@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOrqZ2vjS2MPR9TlRefdFS/YQlkQA8eN8P3wQuhq2eoMnDFv20n+xSe9kPH4ec1/8g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f1368e3d-d4b5-485e-b0cc-4eaf963db54e",
                            TwoFactorEnabled = false,
                            UserName = "alice.johnson@example.com"
                        },
                        new
                        {
                            Id = "22222222-3333-4444-5555-666666666666",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b0cf3a7d-0279-4ce4-afc5-a6bfa5e5065f",
                            Email = "bob.smith@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "BOB.SMITH@EXAMPLE.COM",
                            NormalizedUserName = "BOB.SMITH@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEM5R0m/o8iugxCOAcUvYB1+fAI7Rlfw46nLTs+UfqF4WPre2EHzne7VokIuwCgL1Pg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3fc0aee5-d65b-4b51-a4c8-5029eaa81a65",
                            TwoFactorEnabled = false,
                            UserName = "bob.smith@example.com"
                        },
                        new
                        {
                            Id = "33333333-4444-5555-6666-777777777777",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8a7ec7b2-5905-472a-b56d-3cda5b5c40fc",
                            Email = "employer1@techcorp.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER1@TECHCORP.COM",
                            NormalizedUserName = "EMPLOYER1@TECHCORP.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEC5AieKHIm+1sQEMJjVXwr4LY0rWHb6Fl4BtnJBCLlxkRr+YzvTMdRNCWe2Pl6G8ZQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9f038f50-c7fa-45f3-b210-fce1e09d3085",
                            TwoFactorEnabled = false,
                            UserName = "employer1@techcorp.com"
                        },
                        new
                        {
                            Id = "44444444-5555-6666-7777-888888888888",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "55248409-540e-4860-a236-1fad2fac70db",
                            Email = "employer2@healthplus.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "EMPLOYER2@HEALTHPLUS.COM",
                            NormalizedUserName = "EMPLOYER2@HEALTHPLUS.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEPdUXlP9uNncOHN25kVOPIwvpGZ1eJvi1zVxpcvwN1h/BSwhi+7zNcOblTEQr2KNUg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "85b077b9-804d-42d8-a638-d0f3b99674d2",
                            TwoFactorEnabled = false,
                            UserName = "employer2@healthplus.com"
                        },
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ea016dc8-3743-4669-a4a0-483737f35682",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAED5BXW2RxoWRJUfxMqH8mqsrgeaWYGnxo644SJQSJCt2M9ZhmU0O5YQR3EJ61WNW3A==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b50a3831-a053-4737-9a08-14a3343587c4",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c3a1f2d4-9b8e-4a21-a1b2-01f0e5d6c789",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "d7e4c1b2-8a9f-4c33-b1a0-92e4f6d8c123",
                            Name = "Employer",
                            NormalizedName = "EMPLOYER"
                        },
                        new
                        {
                            Id = "e9b7a3d2-5f61-4c9b-8a11-0b3f8c4e5678",
                            Name = "JobSeeker",
                            NormalizedName = "JOBSEEKER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "c3a1f2d4-9b8e-4a21-a1b2-01f0e5d6c789"
                        },
                        new
                        {
                            UserId = "33333333-4444-5555-6666-777777777777",
                            RoleId = "d7e4c1b2-8a9f-4c33-b1a0-92e4f6d8c123"
                        },
                        new
                        {
                            UserId = "44444444-5555-6666-7777-888888888888",
                            RoleId = "d7e4c1b2-8a9f-4c33-b1a0-92e4f6d8c123"
                        },
                        new
                        {
                            UserId = "11111111-2222-3333-4444-555555555555",
                            RoleId = "e9b7a3d2-5f61-4c9b-8a11-0b3f8c4e5678"
                        },
                        new
                        {
                            UserId = "22222222-3333-4444-5555-666666666666",
                            RoleId = "e9b7a3d2-5f61-4c9b-8a11-0b3f8c4e5678"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Application", b =>
                {
                    b.HasOne("JobBoard.Components.Domain.JobListing", "JobListing")
                        .WithMany()
                        .HasForeignKey("JobListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBoard.Data.JobBoardUser", "JobSeeker")
                        .WithMany()
                        .HasForeignKey("JobSeekerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobListing");

                    b.Navigation("JobSeeker");
                });

            modelBuilder.Entity("JobBoard.Components.Domain.Employer", b =>
                {
                    b.HasOne("JobBoard.Data.JobBoardUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobBoard.Components.Domain.FeedBack", b =>
                {
                    b.HasOne("JobBoard.Data.JobBoardUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JobBoard.Components.Domain.JobListing", b =>
                {
                    b.HasOne("JobBoard.Components.Domain.Employer", "Employer")
                        .WithMany()
                        .HasForeignKey("EmployerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employer");
                });

            modelBuilder.Entity("JobBoard.Components.Domain.JobSeeker", b =>
                {
                    b.HasOne("JobBoard.Data.JobBoardUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("JobBoard.Data.JobBoardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("JobBoard.Data.JobBoardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobBoard.Data.JobBoardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("JobBoard.Data.JobBoardUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
